name: Build and deploy package

# Quando vai executar
on:
  push:
    branches:
      - main

# Onde vai rodar
jobs:
  build-and-deploy:
    runs-on: ubunto-latest

#Pegar o codigo fonte da raiz do repositorio
    steps:
    - uses: actions/checkout@main
# Instalando .net na maquina
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
# Buildando    
    - name: Build with dotnet
      run: dotnet build --configuration Release
# Rodando o teste
    - name: Test
      run: dotnet test
# Criando pacote
    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run dotnet nuget push "MoneyExtension/bin/release/*.nupkg" -k ${{secret.NUGET_TOKEN}} -s http://api.nuget.org.v4/index.json

